#ifndef _QD_DEFINITIONS_H_
#define _QD_DEFINITIONS_H_

#define DISPLAY_TIME_SPLASH_SCENE 2
#define TRANSITION_TIME 0.5
#define PIPE_SPAWN_FREQUENCY 0.0015

#define PIPE_GAP 5
#define UPPER_SCREEN_PIPE_THRESHOLD 0.85
#define LOWER_SCREEN_PIPE_THRESHOLD 0.45

#define PIPE_MOVEMENT_SPEED 0.005

#define DUCK_COLLISION_BITMASK 0x000001
#define OBSTACLE_COLLISION_BITMASK 0x000002
#define POINT_COLLISION_BITMASK 0x000003

#define DUCK_FALLING_SPEED 0.005
#define DUCK_FLYING_SPEED 0.005
#define DUCK_FLY_DURATION 0.5

#define SCORE_FONT_SIZE 0.2

#endif // _QD_DEFINITIONS_H_
